### ISSUE TITLE
在什么平台测试呢？

### ISSUE THREAD

**Issue by qianguozheng** [gozfree/aquila#1]
通用Linux上面就可以运行测试吗?

**Comment by gozfree** [comment]
ubuntu上接个usbcam就行

**Comment by qianguozheng** [comment]
很好的思路，希望能成功，我已经好几年不搞ip camera了。。。

**Comment by tinycake** [comment]
如果能做成几个常见嵌入式方案的适配，可玩性就高多了。

**Comment by gozfree** [comment]
是的，初步先支持raspberrypi，以及主流大厂的hisi，amba平台，欢迎更多同学填坑
