### ISSUE TITLE
lua5.2 was not found 

### ISSUE THREAD

**Issue by pzibang** [gozfree/aquila#2]
执行build.sh的时候提示错误：
Package lua5.2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua5.2.pc'
to the PKG_CONFIG_PATH environment variable

按照：https://www.jianshu.com/p/0ba41cf0403c的做法安装了lua再次执行也还是提示相同的错误

**Comment by gozfree** [comment]
> 执行build.sh的时候提示错误：
> Package lua5.2 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `lua5.2.pc'
> to the PKG_CONFIG_PATH environment variable
> 
> 按照：[https://www.jianshu.com/p/0ba41cf0403c的做法安装了lua再次执行也还是提示相同的错误](https://www.jianshu.com/p/0ba41cf0403c%E7%9A%84%E5%81%9A%E6%B3%95%E5%AE%89%E8%A3%85%E4%BA%86lua%E5%86%8D%E6%AC%A1%E6%89%A7%E8%A1%8C%E4%B9%9F%E8%BF%98%E6%98%AF%E6%8F%90%E7%A4%BA%E7%9B%B8%E5%90%8C%E7%9A%84%E9%94%99%E8%AF%AF)

试试
sudo apt-get install liblua5.2-dev
