### ISSUE TITLE
缺少头文件flv_mux.h

### ISSUE THREAD

**Issue by pzibang** [gozfree/aquila#3]
执行make的时候提示错误：
In file included from src/librtmpc.c:22:0:
./include/librtmpc.h:35:21: fatal error: flv_mux.h: No such file or directory
 #include "flv_mux.h"

**Comment by gozfree** [comment]
更新gear-lib代码后，执行如下命令:
$ cd gear-lib
$ ./bulld.sh
$ sudo ./build.sh install
